blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using notify
    url: https://github.com/projectdiscovery/notify/discussions/categories/q-a
    about: Ask a question or request support for using notify

  - name: Share idea / feature to discuss for notify
    url: https://github.com/projectdiscovery/notify/discussions/categories/ideas
    about: Share idea / feature to discuss for notify

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication